Version: 2

Application:
  ?:
    type: io.murano.apps.docker.DockerMariaDB
  name: $.appConfiguration.name
  host: $.appConfiguration.host 
  port: $.appConfiguration.port
  publish: $.appConfiguration.publish
  password: $.appConfiguration.password
  

Forms:
  - appConfiguration:
      fields:
        - name: name
          type: string
          label: Application Name
          initial: 'DockerMariaDB'
          description: >-
            Enter a desired name for the application. Just A-Z, a-z, 0-9, dash and
            underline are allowed
        - name: host
          type:
            - io.murano.apps.docker.kubernetes.KubernetesPod
            - io.murano.apps.docker.DockerStandaloneHost
          label: Container Host
          description: >-
            Select an instance of Docker contaniner hosting provider to run the app
        - name: password
          type: password
          required: true
          label: MySQL Password
          description: >-
            Password for root user in MySQL
        - name: port
          type: integer
          label: Port
          minValue: 1
          maxValue: 65535
          initial: 3306
          description: >-
            Select a port to run the app
        - name: publish
          type: boolean
          label: Make application accessible from outside
          initial: false
          required: true
