Format: 1.0
Type: Library
FullName: io.murano.apps.docker.Interfaces
Name: Docker Services Library
Description: |
 The library provides all necessary interface classes for Docker
and Kubernetes Services
Author: 'Mirantis, Inc'
Tags: [Docker, Kubernetes]
Classes:
 io.murano.apps.docker.DockerContainerHost: DockerContainerHost.yaml
 io.murano.apps.docker.DockerHelpers: DockerHelpers.yaml
 io.murano.apps.docker.DockerHostVolume: DockerHostVolume.yaml
 io.murano.apps.docker.DockerTempVolume: DockerTempVolume.yaml
 io.murano.apps.docker.DockerVolume: DockerVolume.yaml
 io.murano.apps.docker.ApplicationPort: ApplicationPort.yaml
