Namespaces:
  =: io.murano.apps.docker
  std: io.murano

Name: DockerContainerHost

Extends: std:Application

Properties:
  name:
    Contract: $.string().notNull()

Methods:
  hostContainer:
    Arguments:
      - applicationName:
          Contract: $.string().notNull()
      - image:
          Contract: $.string().notNull()
      - commands:
          Contract: 
            - $.string().notNull()
          Default: []
      - env:
          Contract:
            $.string().notNull(): $.string().notNull()
          Default: {}
      - ports:
          Contract: 
            - $.class(ApplicationPort)
          Default: []
      - volumes:
          Contract:
            $.string().notNull(): $.class(DockerVolume).notNull()
          Default: {}


  deleteContainer:
    Arguments:
      - name:
          Contract: $.string().notNull()

  getEndpoints:
    Arguments:
      - applicationName:
          Contract: $.string().notNull()
